#!/usr/bin/env ansible-playbook
---
- name: configures vim
  hosts: localhost
  connection: local
  tasks:
    - name: install apt packages
      action: apt pkg={{ item }} state=present
      become: yes
      with_items:
        - cmake
        - exuberant-ctags
        - git
        - python-dev
        - rsync
        - silversearcher-ag

        # Dependencies for apt_repository
        - python-apt
        - python-pycurl
      when: no_sudo is not defined

    - apt_key: id=941C42E6
      become: yes
      when: no_sudo is not defined

    - apt_repository: repo='deb http://debian.sur5r.net/neovim stretch main'
      become: yes
      when: no_sudo is not defined

    - name: install neovim from above repo
      action: apt pkg={{ item }} state=present
      become: yes
      with_items:
        - neovim
        - python3-neovim
      when: no_sudo is not defined

    - name: create symlink to point Vim to Neovim config directory
      file: state=link src=~/.config/nvim dest=~/.vim

    - name: create symlink to point Vim to Neovim init script
      file: state=link src=~/.config/nvim/init.vim dest=~/.vimrc

    - name: install dein, which manages vim plugins
      git: repo=https://github.com/Shougo/dein.vim.git
           dest=~/.cache/dein/repos/github.com/Shougo/dein.vim
           update=no

    - name: install plugins
      shell: nvim -c "try | call dein#install() | finally | qall! | endtry" -i NONE +q
