#!/usr/bin/env ansible-playbook
---
- name: configures vim
  hosts: localhost
  connection: local
  tasks:
    - name: install apt packages
      action: apt pkg={{ item }} state=present
      become: yes
      with_items:
        - fd-find
        - cmake
        - exuberant-ctags
        - git
        - python-dev
        - ripgrep
        - rsync

        # Dependencies for apt_repository
        - python-apt
        - python-pycurl

        - neovim
        - python3-neovim
      when: no_sudo is not defined

    - name: create symlink to point Vim to Neovim config directory
      file: state=link src=~/.config/nvim dest=~/.vim

    - name: create symlink to point Vim to Neovim init script
      file: state=link src=~/.config/nvim/init.vim dest=~/.vimrc

    - name: install vim-plug, which manages vim plugins
      run:
        sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

    - name: install plugins
      shell: nvim -c "try | PlugInstall | finally | qall! | endtry" -i NONE +q
