#!/usr/bin/env ansible-playbook
---
- name: configures vim
  hosts: localhost
  connection: local
  tasks:
    - name: install apt packages
      action: apt pkg={{ item }} state=present
      sudo: yes
      with_items:
        - exuberant-ctags
        - cmake
        - python-dev
        - silversearcher-ag
        - npm
      when: no_sudo is not defined

    - name: install neobundle, which manages vim plugins
      git: repo=https://github.com/Shougo/neobundle.vim.git
           dest=~/.vim/bundle/neobundle.vim
           update=no

    - name: install plugins
      shell: ~/.vim/bundle/neobundle.vim/bin/neoinstall

    - name: create symlink to point Neovim to Vim config directory
      file: state=link src=~/.vim dest=~/.config/nvim

    - name: create symlink to point Neovim to Vim init script
      file: state=link src=~/.vimrc dest=~/.config/nvim/init.vim
